export const cities = [
  {
    name: "Minneapolis",
    id: 1,
    state: "Minnesota",
    population: 382578,
    nicknames: ["City of Lakes", "Mill City", "Twin Cities", "Mini Apple"],
  },
  {
    name: "Chicago",
    id: 2,
    state: "Illinois",
    population: 2695598,
    nicknames: [
      "Windy City",
      "Chi-Town",
      "Second City",
      "City of the Big Shoulders",
    ],
  },
  {
    name: "Philadelphia",
    id: 3,
    state: "Pennsylvania",
    population: 1526006,
    nicknames: [
      "Philly",
      "The City of Brotherly Love",
      "The Athens of America",
      "The Birthplace of America",
      "Filthydelphia",
    ],
  },
  {
    name: "Los Angeles",
    id: 4,
    state: "California",
    population: 3792621,
    nicknames: [
      "L.A.",
      "City of Angels",
      "The Entertainment Capital of the World",
      "La-la-land",
      "Tinseltown",
    ],
  },
  {
    name: "Portland",
    id: 5,
    state: "Oregon",
    population: 583776,
    nicknames: [
      "Rose City",
      "The City of Roses",
      "Bridgetown",
      "Stumptown",
      "Rip City",
      "Soccer City",
      "P-Town",
      "Portlandia",
      "Little Beirut",
    ],
  },
];
